# Core包配置 - DbRheo核心业务逻辑

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dbrheo-core"
version = "1.0.0"
description = "DbRheo数据库Agent核心包"
authors = [{name = "DbRheo Team", email = "team@dbrheo.com"}]
license = {text = "MIT"}
requires-python = ">=3.9"
dependencies = [
    # AI和API
    "google-generativeai>=0.8.3",
    "google-auth>=2.35.0",
    
    # 数据库相关
    "sqlalchemy[asyncio]>=2.0.36",
    "asyncpg>=0.30.0",
    "aiomysql>=0.2.0",
    "aiosqlite>=0.20.0",
    
    # 核心依赖
    "pydantic>=2.10.0",
    "pyyaml>=6.0.2",
    "httpx>=0.28.0",
    "aiofiles>=24.1.0"
]

[project.optional-dependencies]
mcp = [
    "mcp>=1.0.0"
]
dev = [
    "pytest>=8.3.0",
    "pytest-asyncio>=0.24.0",
    "black>=24.10.0",
    "mypy>=1.13.0",
    "ruff>=0.8.0"
]

[tool.setuptools.packages.find]
where = ["src"]
include = ["dbrheo*"]

[tool.setuptools.package-dir]
"" = "src"
